name: flutter_ethers
description: A starting point for Dart libraries working with Ethers.js .
version: 1.0.2
homepage: https://pub.dev/packages/flutter_ethers
repository: https://github.com/HydraIndustriesOfficial/flutter_ethers

environment:
  sdk: '>=2.18.4 <3.0.0'

dependencies:
  web3dart: ^2.4.1
  ens_dart: ^1.0.0
  provider: ^6.0.4
  bip39: ^1.0.6
  decimal: ^2.3.0
  bip32: ^2.0.0
  convert: ^3.1.1
  pointycastle: ^3.6.2
  http: ^0.13.6
  meta: ^1.8.0

dev_dependencies:
  lints: ^3.0.0
  test: ^1.16.0
